---
mixed-port: 7890
allow-lan: false
mode: Global
log-level: silent
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://cloudflare-dns.com/dns-query
  - https://dns.adguard.com/dns-query
  fallback:
  - https://cloudflare-dns.com/dns-query
  - https://dns.adguard.com/dns-query
proxy-groups:
- name: "\U0001F525 Auto"
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: "\U0001F530 Select"
  type: select
  proxies:
  - "\U0001F525 Auto"
  - "✅ Direct"
- name: "✅ Direct"
  type: select
  proxies:
  - DIRECT
- name: "\U0001F6AB Intercept"
  type: select
  proxies:
  - REJECT
  - DIRECT
rule-providers:
  iran:
    type: http
    behavior: classical
    url: https://github.com/SamadiPour/iran-hosted-domains/releases/latest/download/clash_rules.yaml
    path: "./ruleset/iran.yaml"
    interval: 432000
rules:
- RULE-SET,iran,✅ Direct
- "DOMAIN-SUFFIX,ad.com,\U0001F6AB Intercept"
- SRC-IP-CIDR,192.168.1.201/32,✅ Direct
- IP-CIDR,127.0.0.0/8,✅ Direct
- "MATCH,,\U0001F530 Select,dns-failed"
